# Generated by Django 2.1.5 on 2019-02-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hue_bridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brigde_name', models.CharField(max_length=20)),
                ('bridge_ip_address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorLights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_name', models.CharField(max_length=120)),
                ('light_product_id', models.CharField(max_length=120)),
                ('light_mode', models.CharField(max_length=20)),
                ('light_status', models.BooleanField(default=True, verbose_name='On/Off Status')),
                ('light_bri', models.IntegerField(default=254)),
            ],
        ),
    ]
