# Generated by Django 2.1.5 on 2019-02-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philips_hue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorBridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridge_name', models.CharField(max_length=20)),
                ('bridge_ip_address', models.GenericIPAddressField()),
                ('bridge_localtime', models.DateTimeField()),
                ('bridge_timezone', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='hue_bridge',
        ),
        migrations.AddField(
            model_name='monitorlights',
            name='light_assigned_seq',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
