"""
Django settings for smart_home_project project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
from django.conf import settings
from celery.schedules import crontab
from smart_home_project.utilities import get_env_variable
import logging
import os
from pathlib import Path
from dotenv import load_dotenv, find_dotenv
from decouple import config, Csv

from decouple import config

load_dotenv(find_dotenv())


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: keep the secret key used in production secret!
try:
    SECRET_KEY = config("DJANGO_SECRET_KEY")
except KeyError as e:
    raise RuntimeError(
        "Could not find a Django SECRET_KEY in the environment variables.") from e


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DJANGO_DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('DJANGO_ALLOWED_HOSTS', default="localhost", cast=Csv())

# 'my_app_logs' directory is located at the base of my project
LOGGING_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGGING_DIR):
    os.makedirs(LOGGING_DIR)


# add logging to the project
# src/logs/django.log
LOGGING_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGGING_DIR):
    os.makedirs(LOGGING_DIR)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            # Remember setting to 'INFO' or 'WARNING' for production
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGGING_DIR, 'verbose_app_log.log'),
            'maxBytes': 1024*1024*5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        # Add any other loggers for your app here
        'django.db': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },

        'django.db.backends': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'django.networking': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.mangement_script': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.security': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file', 'console'],
            'level': 'ERROR',
            'propagate': True,
        },
        'philips_hue': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },

}

# set up a logger for the project
logger = logging.getLogger('django')

logger.info(f'the sytem is running in DEBUG mode: {DEBUG}?....')
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'shared_assets')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'timeclock',
    'gunicorn',
    'philips_hue',
    'networking',
    # 'huesdk',
    'celery',
    'django_celery_beat',
    'corsheaders',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'smart_home_project.middlewares.TimezoneMiddleware',
]

ROOT_URLCONF = 'smart_home_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smart_home_project.wsgi.application'

# HUE BRIDGE USERNAME. This is the username that the app will use to connect to the Hue Bridge.


try:
    HUE_BRIDGE_USERNAME = config('HUE_BRIDGE_USERNAME')
    HUE_BRIDGE_USERNAME2 = config('HUE_BRIDGE_USERNAME2')

except KeyError as e:
    # Handle the absence of both variables
    # Log the error or raise an exception with detailed feedback
    raise KeyError(
        "Neither 'HUE_BRIDGE_USERNAME' nor 'HUE_BRIDGE_USERNAME2' found in environment variables...")
if HUE_BRIDGE_USERNAME or HUE_BRIDGE_USERNAME2:
    logger.info('found existing hue bridge usernames in the env...')
# CORS settings
CORS_ALLOWED_ORIGINS = ['http://localhost:5173', 'http://localhost:3000']
# CORS_ALLOWED_ORIGIN_REGEXES = [
#     r"^https://\w+\.ngrok\.io$",
# ]

CORS_ALLOW_ALL_ORIGINS = True

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# Helper function to read environment variables
if DEBUG:

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': get_env_variable('DB_DATABSASE1', default='smart_home_hub', required=True),
            'USER': get_env_variable('DB_APP_USER', required='sa').lower(),
            'PASSWORD': get_env_variable('DB_APP_USER_PASSWORD', required=True),
            'HOST': get_env_variable('DB_SERVER', default='localhost'),
            'PORT': get_env_variable('DB_PORT', default='5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': get_env_variable('DB_DATABSASE1', default='smart_home_hub', required=True),
            'USER': get_env_variable('DB_APP_USER', required=True).lower(),
            'PASSWORD': get_env_variable('DB_APP_USER_PASSWORD', required=True),
            'HOST': get_env_variable('DB_SERVER', default='localhost'),
            'PORT': get_env_variable('DB_PORT', default='5432'),
        }
    }
# DRF setting
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.AllowAny',  # allow any
    ]
}

# use Redis as a cache backend
if DEBUG:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': 'redis://127.0.0.1:6379/1',
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.environ.get('REDIS_URL'),  # Heroku provides this
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }
# session settings: to use Redis as a session bac
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
# This line is usually not necessary as 'default' is used by default
SESSION_CACHE_ALIAS = "default"

# Celery Configuration Options
CELERY_TIMEZONE = "America/Los_Angeles"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
if DEBUG:
    CELERY_BROKER_URL = 'redis://redis:6379/0'
else:
    CELERY_BROKER_URL = config('REDIS_URL')


# user Django ORM to store the schedule in the database
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
# file period_crontab_tasks.py in the philips_hue app

# CELERY_BEAT_SCHEDULE = {
#     'run-save_lights_every-day': {
#         'task': 'phillips.tasks.save_lights_task',
#         'schedule': crontab(hour=7, minute=0),
#         # 'args': (arg1, arg2),  # You can provide additional args if needed
#     },
# }

# CELERY_BEAT_SCHEDULE_FILENAME = 'celerybeat-schedule'

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'
USE_I18N = True

USE_L10N = True

USE_TZ = True
